language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

install:
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

before_script:
    - composer install

script:
    - phpunit
    - phpcs --standard=PSR2 classes/ tests/

